workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      java: 17
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - rolex18k40@gmail.com
