workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
      java: 11
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build and Force Path
        script: |
          export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
          flutter build apk --debug --no-tree-shake-icons
          # Copy to root so Codemagic CANNOT miss it
          cp build/app/outputs/flutter-apk/app-debug.apk ./app-debug.apk
    artifacts:
      - "*.apk"
    publishing:
      email:
        recipients:
          - rolex18k40@gmail.com
