workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
      java: 11
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Force Build APK
        script: |
          export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
          flutter build apk --debug --no-tree-shake-icons
          mkdir -p build/app/outputs/flutter-apk
          find build/app/outputs -name "*.apk" -exec cp {} build/app/outputs/flutter-apk/ \;
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - rolex18k40@gmail.com
