name: right_now_app_v2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+111

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: 10.1.0
  google_sign_in: 6.1.0
  permission_handler: 11.0.0
  flutter_lints: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
